version: "3"
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    restart: on-failure
    build: ./web
    hostname: api
    ports:
      - '81:5000'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    
  client:
    restart: on-failure
    build: ./client
    hostname: client
    ports:
      - '82:3000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - api
    - client


